---
- name: install start and enable httpd
  hosts: all
  tasks:
  - name: install package
    dnf:
      name: httpd
      state: latest
  - name: start and enable servie
    service:
      name: httpd
      state: started
      enabled: yes
- name: test httpd accessibility
  hosts: localhost
  # become: no                        # uncomment to fix
  tasks:
    - name: test httpd access
      uri:
        url: http://server1
        return_content: yes
        status_code: 200
