---
- name: task name here
  become: yes
  hosts: all # you can use limit clause
  tasks:
  - name: install httpd
    dnf:
      name: httpd
      state: present
  
  - name: enable service
    service:
      name: httpd
      state: started
      enabled: yes
