---
- name: install and start the vsftpd service
  hosts: all
  become: yes
  tasks:
    - name: install vsftpd
      dnf:
        name: vsftpd
        state: latest
    - name: start and enable vsftpd
      service:
        name: vsftpd
        state: started
        enabled: yes
