---
- name: install start and enable httpd
  become: yes
  hosts: all # you can use limit clause
  tasks:
  - name: install httpd
    dnf:
      name: httpd
      state: present
  
  - name: start and enable service
    service:
      name: httpd
      state: started
      enabled: yes
