---
- name: demonstrate changed status
  hosts: all
  tasks:
  # will report a status change even though nothing has changed
  - name: check local time
    command: date
    register: command_result
    changed_when: false # uncomment to prevent status change (wills till report ok or failed)
  - name: print local time
    debug:
      var: command_result.stdout