---
- name: create a user with vaulted variables
  hosts: server1
  vars_files:
    - secrets.yaml
  tasks:
    - name: creating user
      user:
        name: "{{ username }}"
        password: "{{ pwhash }}"
