---
- name: using fetch to get log from slave nodes
  hosts: all
  tasks:
  - name: fetching log data
    fetch:
      dest: /tmp
      src: /var/log/wtmp
- name: conciliating the binaries in a single readable file
  hosts: localhost
  vars:
    prefix: /tmp/server
    suffix: /var/log/wtmp
    conciliated_file: allnodes-last.out
  tasks:
  - name: output the log into file
    shell: "last -f {{ prefix }}{{ item }}{{ suffix }} >> /tmp/{{ conciliated_file }}"
    loop: "{{ range(1,3,1)|list }}" # also use - 1\n - 2\n - 3\n - 4\n
  - name: show the conciliated file
    shell: "cat /tmp/{{ conciliated_file }}"
