---
- name: stat module tests
  hosts: server1
  tasks:
    - stat:
        path: /etc/hosts
      register: st
    - name: show current values
      debug:
        msg: current value of the st variable is {{ st }}
