---
- name: test register
  hosts: all
  tasks:
  - shell: cat /etc/passwd
    register: passwd_contents
  - debug:
      msg: passwd contains user lisa
    # only prints the debug message if the passwd_contents.stdout contains the string 'lisa' 
    when: passwd_contents.stdout.find('lisa') != -1